Add a command to create a user from command line
anonaddy/anonaddy pull request #80
Opened 2020-09-22 16:22 UTC by slurdge

I could follow your example of listing user. This command creates a user with (slightly) more powers than the sign-in form.
Especially, there is validation of blacklist of words.
The password is the userid by default. Users should be able to reset the password themselves.

An option could be added to manually validate the mail.

2020-09-25 16:40 UTC, willbrowningme commented
What do you mean by "with (slightly) more powers than the sign-in form"?

Do you mean because this method allows you to create a new user without validating against the username blacklist, so you can use "admin" as the username for example?

2020-09-25 21:29 UTC, slurdge commented
I meant exactly what you describe. Sorry if the wording was poor.

2020-09-26 08:02 UTC, willbrowningme commented
What if I just added a new .env variable that would allow you to ignore the username blacklist during registration so you can just use the normal registration form with any username you like?

For example in `.env`

`ANONADDY_IGNORE_USERNAME_BLACKLIST=true`

2020-09-26 08:21 UTC, slurdge commented
For self-host I much prefer this command as it allows to close registration and manually add users. I do not have this use case right now (I'm open registration) but I'm pretty sure most self host would want such a feature.

Regarding the `.env`, that would work for this specific case, but this creates the same problem as for registration right now. If you want to close registration but still be able to add users, you have to change the .env, restart the docker (if you are on docker), tell the user to create its account/do it yourself, change the .env again. Not exactly user-friendly in my opinion.

First goal of this PR is addressing the need to create users with closed registration/in a more controlled way, additional powers is just a bonus I saw when doing the implementation.

2020-09-26 08:29 UTC, willbrowningme commented
Okay, that makes sense now. I will merge this shortly after I have pushed the upgrade to Laravel 8.

2020-09-26 08:32 UTC, willbrowningme commented on app/Console/Commands/CreateUser.php
> +use App\User;
Please update to `use App\Models\User;` ready for Laravel 8 upgrade.

2020-09-26 08:32 UTC, willbrowningme commented on app/Console/Commands/CreateUser.php
> +use App\Recipient;
Please update to `use App\Models\Recipient;` ready for Laravel 8 upgrade.

2020-09-26 08:33 UTC, willbrowningme commented on app/Console/Commands/CreateUser.php
> +use App\Rules\NotBlacklisted;
Please remove this use statement as this rule is not required.

2020-09-26 08:34 UTC, willbrowningme commented on app/Console/Commands/CreateUser.php
> +    protected $description = 'Create directly an user';
Creates a new user

2020-09-26 08:35 UTC, willbrowningme requested changes
Please could you update according to the comments ready for the Laravel 8 upgrade.

2020-09-26 08:37 UTC, slurdge commented
Yes I will. BTW if you want, you should be able to push your changes directly to my PR, I checked the ability to commit directly to it.
![image](https://user-images.githubusercontent.com/1651201/94336525-236a0b00-ffe4-11ea-9bde-d9dfcec0607b.png)

2020-09-26 08:39 UTC, slurdge commented
Changes are made ✔️

2020-09-26 08:40 UTC, willbrowningme approved these changes

2020-09-27 14:14 UTC, merged